"""NCP NVRAM related helpers."""
import logging

import zigpy_zboss.commands as c
import zigpy_zboss.types as t

LOGGER = logging.getLogger(__name__)


class NVRAMHelper:
    """Class used for NVRAM read/write."""

    def __init__(self, zboss):
        """Create class object."""
        self.zboss = zboss

    async def read(self, nv_id: t.DatasetId, item_type):
        """Read a NVRAM dataset."""
        res = await self.zboss.request(
            c.NcpConfig.ReadNVRAM.Req(
                TSN=self.zboss._app.get_sequence(),
                DatasetId=nv_id
            )
        )
        if res.StatusCode != 0:
            return None

        if not res.DatasetId == nv_id:
            raise

        if item_type:
            value, _ = item_type.deserialize(res.Dataset.serialize())
            LOGGER.debug('Read NVRAM [0x%04x] = %r', nv_id.value, value)
            return value

    async def write(self, nv_id: t.DatasetId, dataset_obj):
        """Write a NVRAM dataset.

        The firmware stores datasets at the exact length it is given (a read
        of e.g. ZB_NVRAM_COMMON_DATA returns the precise byte count, never a
        padded blob). The dataset structs carry a leading ``byte_count`` field
        that maps onto the NVRAMDataset length prefix, so it is stripped here
        and regenerated by the LVList. Writing the exact size is important:
        handing the firmware an over-sized dataset (e.g. a fixed 280 byte
        blob) makes ZBOSS fault while parsing NVRAM on the next boot, which
        bricks the NCP until its NVRAM is erased and re-flashed.

        We deliberately do NOT read the dataset back here to verify it. While
        the stack is running, NVRAM_READ is served from the stack's in-RAM
        working copy, whereas NVRAM_WRITE updates flash without touching that
        copy. An immediate read-back therefore returns the stale value (or
        NOT_FOUND if the dataset did not exist yet); the written value only
        becomes visible after a reset reloads NVRAM into RAM. Callers that
        need the value to take effect issue a reset, after which zigpy
        re-reads the state via ``load_network_info``.
        """
        serialized_ds_obj = dataset_obj.serialize()[2:]
        dataset = t.NVRAMDataset(serialized_ds_obj)

        rsp = await self.zboss.request(
            c.NcpConfig.WriteNVRAM.Req(
                TSN=self.zboss._app.get_sequence(),
                DatasetCnt=1,
                DatasetId=nv_id,
                Version=dataset_obj.version,
                Dataset=dataset
            )
        )

        if rsp.StatusCode != 0:
            LOGGER.warning(
                "NVRAM write of dataset [0x%04x] returned a non-OK status: "
                "%s/%s",
                nv_id.value,
                rsp.StatusCat,
                rsp.StatusCode,
            )
