name: Publish distributions to TestPyPI
on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    name: Build and publish distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install wheel
      run: >-
        pip install wheel build
    - name: Build wheel
      run: >-
        python3 -m build
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/